### ISSUE TITLE
The content of the message has images, which are not displayed in the string representation

### ISSUE THREAD

**Issue by recursix** [ServiceNow/AgentLab#135]
Either we are not using it correctly for the vision agent, or there is another part of the code that just puts it as string for e.g. token count and it shows this warning.  

![image](https://github.com/user-attachments/assets/86d7d8e4-5dc7-4138-b6a0-242b69da4519)

**Comment by ThibaultLSDC** [comment]
Should come from token fitting here: https://github.com/ServiceNow/AgentLab/blob/096cb59ed581d97c74607a0f86f6c9779a80be0c/src/agentlab/agents/dynamic_prompting.py#L263

I can confirm that the screenshot is in the prompt here if the use_screenshot flag is True:
https://github.com/ServiceNow/AgentLab/blob/096cb59ed581d97c74607a0f86f6c9779a80be0c/src/agentlab/agents/generic_agent/generic_agent.py#L116

**Comment by ThibaultLSDC** [comment]
We could tune down the warning to an info

**Comment by ThibaultLSDC** [comment]
Suggestion done here https://github.com/ServiceNow/AgentLab/pull/136 @recursix
