### ISSUE TITLE
Pin Gradio to 5.0+

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/AgentLab#140]
It appears the latest version of agentlab uses features from gradio 5.0+, such as max_height: https://github.com/ServiceNow/AgentLab/blob/5d72e8b023ca80a8eb5719e83b2e42566055247f/src/agentlab/analyze/agent_xray.py#L225

It would be great to pin it in the setup.py

**Comment by recursix** [comment]
It's already pinned for gradio>=5.5
Prehaps update the setup?

**Comment by xhluca** [comment]
Awesome
