### ISSUE TITLE
WorkArena AGENT_4o performance & SOM viewport resolution

### ISSUE THREAD

**Issue by Serega6678** [ServiceNow/AgentLab#15]
Hey guys @ThibaultLSDC @recursix ! Thank you for your impressive work! I

I was trying to run your code and noticed several weird things, that I wanted to clarify them:

1. I run AGENT_4o (I assume this is the text-only GPT-4o agent from the paper) and got around 32% if I average over all trajectories. In your paper you reported 40+%. What am I missing?

I launched using this command:
`    python src/agentlab/experiments/launch_exp.py  \
        --exp_config=agentlab.agents.generic_agent.final_run \
        --agent_config=agentlab.agents.generic_agent.AGENT_4o \
        --benchmark=miniwob \
        --n_jobs=-1
 `

The only thing I know I changed is adding timeout to the env so that after each action, the env waits for 10 seconds for the page to load (before normally the observations, both image and text, were sometimes taken from the loading page)
Am I launching the code correctly?

2. When running, the agent saves its screenshots. When I open them, I noticed that their resolution is quite high (2560 × 1440) and the SOM overlay is almost not visible. I assume, when running your experiments, you were using a certain viewport/screen resolution for which you developed your SOM overlay. What was this resolution.

Many thanks for your impressive work once again!

**Comment by Serega6678** [comment]
@yiweifengyan sorry, what is this?

**Comment by recursix** [comment]
@Serega6678, thanks for reporting the drop of performance. It might have happened from a refactoring from 0.1 to 0.2. We will investigate as it is important for us to ensure reproducibility. If it is urgent for you, you can try version 0.1 of the repo, however, the high level API will not be exactly the same. 

I'm currently pushing a new version with more unit-test, and the refactoring should not have affected the agent. But we will investigate further.

**Comment by Serega6678** [comment]
@recursix thank you very much
Do you have information about the resolution of the viewport you used for the vision model?

**Comment by recursix** [comment]
I didn't specify any viewport, I was using the default one. There might have been a PR that changed the default values though. Also, the vision part didn't help much on our side, so this should not explain the 32% vs 42%. 

We will fave to re-run experiments before ICLR, if it's no longer reproducible, we'll have to figure out what happened. Stay tuned.

**Comment by Serega6678** [comment]
@recursix I looked at the trajectories and noticed that out of 225 failed trajectories, around 25% had the len < 16 meaning that the execution stopped earlier (probably due to the timeout 30 sec from browser gym). I will try to start catching this exception instead of crashing an agent
