### ISSUE TITLE
Fix AttributeError in `GenericAgentArgs.set_benchmark`: Incorrect Reference to `action_set`

### ISSUE THREAD

**Issue by rowingchenn** [ServiceNow/AgentLab#157]
In the `set_benchmark` method of the `GenericAgentArgs` class, there is an error in the code:

The code incorrectly attempts to access `GenericAgentArgs.action_set`, but the `GenericAgentArgs` class does not have an attribute named `action_set`. 

The correct implementation should be:

```python
self.flags.action.action_set.demo_mode = "all_blue"
```

**Comment by recursix** [comment]
Thanks @rowingchenn , fixed in PR #175
