### ISSUE TITLE
Considering change default agent to 4o-mini

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/AgentLab#27]
Right now, it's defaulted to 4o

https://github.com/ServiceNow/AgentLab/blob/463b14103725b6137aa24c0e9b4667de2a7d3c9d/src/agentlab/ui_assistant.py#L43C18-L43C56

However, 4o-mini would be much cheaper (15x). Perhaps it's worth consdering using the 4o-mini model as the default LLM?

**Comment by ThibaultLSDC** [comment]
Addressed in #28 
Thanks @xhluca !
