### ISSUE TITLE
Fix gradio sorting and balcklist versions

### ISSUE THREAD

**Issue by recursix** [ServiceNow/AgentLab#51]
Gradio table sorting is supposed to be fixed in a most recent PR. 
* Let's verify if it's merged in main and which versions
* If it's available, let's modify agent-xray to make sure in can properly sort tables
* Also, some version of gradio does some weird reshaping of the tables as we scroll. Let's make sure requirements.txt contains only valid gradio versions.

**Comment by ThibaultLSDC** [comment]
gradio 5.5 supposedly solves the issue
