### ISSUE TITLE
Change get_std_err to fit non binary reward tasks

### ISSUE THREAD

**Issue by ThibaultLSDC** [ServiceNow/AgentLab#54]
The assert in get_std_err (inspect_result.py) is causing problems when reward are not integers, eg w/ weblynx.
We might want to go for empirical std instead, or add an exception to switch to empirical std

**Comment by recursix** [comment]
We should calculate it like this
```python
std_dev = np.std(data, ddof=1)

# Calculate the number of observations
n = len(data)

# Calculate the standard error
standard_error = std_dev / np.sqrt(n)
```
