### ISSUE TITLE
Avoid throwing an error when reward is not 0 or 1

### ISSUE THREAD

**Issue by xhluca** [ServiceNow/AgentLab#55]
Right now this is causing the issue:

https://github.com/ServiceNow/AgentLab/blob/adfcb8c25c464360fb3447bbb96b6500ae784ad8/src/agentlab/analyze/inspect_results.py#L245

We just need to switch from bernouilli to student t-test

**Comment by ThibaultLSDC** [comment]
Fixed in https://github.com/ServiceNow/AgentLab/pull/56
