### ISSUE TITLE
add_screenshot method not working

### ISSUE THREAD

**Issue by alzambranolu13** [ServiceNow/AgentLab#72]
When setting use_screenshot to True I get the following error when trying to run a simple instruction: 
```
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Missing required parameter: 'messages[1].role'.", 'type': 'invalid_request_error', 'param': 'messages[1].role', 'code': 'missing_required_parameter'}}
```
Seems to be the API call needs to be updated.

**Comment by xhluca** [comment]
@alzambranolu13 can you share your environment with `pip freeze > requirements.txt`?

**Comment by recursix** [comment]
@alzambranolu13 , can you confirm this is still an issue with the dev branch

**Comment by alzambranolu13** [comment]
The new branch fixed this, thanks!
