### ISSUE TITLE
Code crushed - need dependecies' versions

### ISSUE THREAD

**Issue by Serega6678** [ServiceNow/AgentLab#8]
Hey guys!

Could you please add dependencies version because I keep getting the error
`cannot import name 'get_all_tasks_agents' from 'browsergym.workarena'`
Which comes from the incompatible version of browsergym

Thanks!

**Comment by ThibaultLSDC** [comment]
Oh now I understad your issue.
This version of agentlab runs on the latest browsergym.workarena version:
[https://github.com/ServiceNow/WorkArena/tree/workarena-plus-plus](url)
I recommend you do the following to setup you environment and run on WorkArena:
```shell
pip install -r requirements.txt
```
Clone and install the workarena++ branch:
```shell
git clone https://github.com/ServiceNow/WorkArena.git
cd WorkArena
pip install -e .
```
Then go back to the agentlab repo and install as an editable.

I am sorry for the misunderstanding, I will push for the Workarena++ release and update the doc in the meantime.

Hope this helps @Serega6678

**Comment by Serega6678** [comment]
@ThibaultLSDC Thank you very much :) I am waiting for the release!

P.S. For your information, the current workarena++ branch misses the is_agent_curriculum variable in the browsergym.workarena.get_all_tasks_agents function that is used in the AgentLabs task_collections file
